[colors]
foreground = "#c3c7c6"
background = "#11211c"
cursor_bg = "#218fa8"
cursor_border = "#9ca5a9"
cursor_fg = "#7491aa"
selection_bg = "#134caa"
selection_fg = "#4e70a9"
ansi = ["#11211c","#5aa990","#218fa8","#9ca5a9","#7491aa","#134caa","#4e70a9","#c3c7c6"]
brights = ["#4c5854","#87fdd8","#31d6fc","#eaf7fd","#aed9ff","#1c71ff","#75a8fd","#f9fffd"]
